version: '3.2'
services:
  zookeeper:
    image: boco/alpine-zookeeper:3.4.9
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: boco/alpine-kafka:1.0.1
    hostname: kafka
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
    links:
      - zookeeper